### ISSUE TITLE
Can we use the snapshot 1.0.0? Do we have to make any changes when using contour layout?

### ISSUE THREAD

**Issue by xiaoqian0408** [cashapp/contour#101]
Hi, there
 
Can I ask a question? just noticed that 1.0.0 snapshot was released, so I was wondering if we can use it, any bugs were fixed or behavior changes in this snapshot?

By the way, is the new release coming soon?

thanks

**Comment by saket** [comment]
We plan to make v1.0 release very soon. If you're comfortable using preview version of libraries in your project then sure go ahead.
