### ISSUE TITLE
Support foreground on API below 23

### ISSUE THREAD

**Issue by omainegra** [cashapp/contour#119]
Since `ContourLayout` extends `ViewGroup`, it doesn't support `foreground` on API below 23, a common workaround is to wrap the layout in a `FrameLayout`, but this seems redundant

**Comment by omainegra** [comment]
An initial backport using https://gist.github.com/JakeWharton/0a251d67649305d84e8a seems to work.

Given 
```kotlin
foreground = ColorDrawable(0xBB000000.toInt())
```
in `ExpandableBioCard2` layout

Result

![Screen Shot 2021-02-03 at 12 34 21 PM](https://user-images.githubusercontent.com/7846263/106793126-afd4ac00-661c-11eb-8191-80fcacae766e.png)

**Comment by saket** [comment]
Agree that having support for foregrounds would be nice, but I also can't help think that supporting API 21 and 22 are not worth it anymore. It's only a matter of time for most apps to drop support for them and any effort invested into them is going to waste. Happy to be convinced otherwise!

**Comment by omainegra** [comment]
Fair enough, I really don't have an argument to support API 21 more than user adoption, we have plans to bump `minSdk` as well... eventually
