### ISSUE TITLE
Int.xdip/Int.ydip & Float.xdip/Float.ydip cause crash on Kotlin 1.4.30

### ISSUE THREAD

**Issue by luis-cortes** [cashapp/contour#123]
This can be easily reproduced by changing the dependency on the sample app from the module to the binary:
`implementation project(':contour')` ->  `implementation 'app.cash.contour:contour:1.0.0'`

Here's the stack trace:
```
java.lang.NoSuchMethodError: No virtual method getYdip-dBGyhoQ(I)I in class 
Lcom/squareup/contour/sample/SampleView; or its super classes (declaration of 
'com.squareup.contour.sample.SampleView' appears in /data/app/~~0Ba-
93BI78uARYazH4agJA==/com.squareup.contour.sample-VKrVvhwusycb2ElCbF70RQ==/base.apk!classes2.dex)
        at com.squareup.contour.sample.SampleView$3.invoke(SampleView.kt:56)
```

`Int.dip` doesn't seem to be an issue.

At least on my project, reverting to 1.4.21 fixes the issue immediately.

**Comment by luis-cortes** [comment]
cc @saket @aerb

**Comment by saket** [comment]
We [bumped up](https://github.com/cashapp/contour/commit/adb8ad3b7539d9eb531c4ff7132fda18375b20dd) Kotlin to 1.4.30 but it's not released yet. Wanna try out `1.1.0-SNAPSHOT` in the meantime?

**Comment by omainegra** [comment]
Do you have plans to release the stable `1.1.0` version soon? Kotlin `1.4.31` was already released last week. BTW snapshot version works fine

**Comment by shekita88** [comment]
> We [bumped up](https://github.com/cashapp/contour/commit/adb8ad3b7539d9eb531c4ff7132fda18375b20dd) Kotlin to 1.4.30 but it's not released yet. Wanna try out `1.1.0-SNAPSHOT` in the meantime?

**Comment by saket** [comment]
Yep, we'll make a release soon!

**Comment by oldergod** [comment]
1.1.0 has been released.
