### ISSUE TITLE
Add more tests around our public API

### ISSUE THREAD

**Issue by oldergod** [cashapp/contour#128]
There are methods in XFloat/YFloat/XInt/YInt which do not have tests. Let's add some.

**Comment by dongheeleeme** [comment]
Hi @oldergod 😄 I'll raise a pr as my first contribute. Should i be assigned? Thanks!

**Comment by oldergod** [comment]
@dongheeleeme Thanks a lot, go ahead. No need to assign.

**Comment by dongheeleeme** [comment]
Awesome, I raised a pr. thanks!
