### ISSUE TITLE
Allow constraints to use the other axis

### ISSUE THREAD

**Issue by sellmair** [cashapp/contour#14]
It would be pretty cool to use information about the other Axis to build constraints. 
E.g. Imagine building a square like: 

```kotlin    

    private val square = View(context).applyLayout(
        x = leftTo { parent.left() }.rightTo { parent.right() },
        y = topTo { parent.bottom() }.heightOf { width().toY() }
    )
 
```

This would currently fail, because of "circular reference".

**Comment by aerb** [comment]
This should work if you call applyLayout within an apply block

**Comment by llywuchen** [comment]
You could try this :https://github.com/Swift-Android/SnapKit-Android

**Comment by saket** [comment]
+1

**Comment by aerb** [comment]
Should achieve what you are looking for. Feel free to reopen if this is not the case.
```
private val square = View(context).apply {
  applyLayout(
        x = leftTo { parent.left() }.rightTo { parent.right() },
        y = topTo { parent.top() }.heightOf { width().toY() }
    )
}
```

**Comment by paolovalerdi** [comment]
I came across this issue today, I tried  to use @aerb solution but it won't work for me

**Comment by jamolkhon** [comment]
#115
