### ISSUE TITLE
Readme Example Seems Wrong

### ISSUE THREAD

**Issue by eygraber** [cashapp/contour#21]
In the code, the example shows the name being constrained to the top:

```
y = topTo { parent.top() + 15.dip }
```

With the avatar being constrained below it:

```
y = topTo { name.bottom() }
```

But the gif shows it constrained to the bottom with the avatar above it.

**Comment by aerb** [comment]
Yeah - that example could use a little cleanup. Will address 👍

**Comment by saket** [comment]
@eygraber wanna send a PR?

**Comment by saket** [comment]
Obsolete eith #104
