### ISSUE TITLE
Usage in lists

### ISSUE THREAD

**Issue by PaulWoitaschek** [cashapp/contour#22]
Some of the points that are great with contour which are stated in the readme are:
* > ViewHolders aren’t needed
* > Add & remove components based on app state
* > Lazy loading elements of the UI.

These points together sound like this layout could replace recycler views.

In the application I'm currently working on about 95% of the screens are scrollable lists, so basically every screen is made of a single RecyclerView.

How is this library designed to be used? Would you use one contourlayout inside a each `ViewHolder`?

**Comment by AlecStrong** [comment]
I wouldn't use ContourLayout to replace RecyclerView...the actual recycling that RecyclerView does is crazy useful. Using ContourLayout as the root of rows in a recyclerview makes tons of sense to me though

**Comment by aerb** [comment]
Agreed with @AlecStrong 's comment. The reason I say ViewHolders are not needed is because you don't need findviewbyid so there is no penalty to accessing fields directly.

**Comment by llywuchen** [comment]
support list you could try this:https://github.com/Swift-Android/SnapKit-Android
