### ISSUE TITLE
ContourLayout and existing Layouts

### ISSUE THREAD

**Issue by FunnyDevs** [cashapp/contour#23]
Is it possibile to add a ContourLayout to an existing layout? When i try to add it to a FrameLayout i obtain ths exception:

`java.lang.ClassCastException: com.squareup.contour.ContourLayout$LayoutSpec cannot be cast to android.view.ViewGroup$MarginLayoutParams`

**Comment by aerb** [comment]
Could you give the could snippet? This sounds wrong.

**Comment by FunnyDevs** [comment]
I have found my bug: i call 'applylayout' after the layout is added to my FrameLayout. I can close the issue
