### ISSUE TITLE
Easier MATCH_PARENT AxisSolver

### ISSUE THREAD

**Issue by gumil** [cashapp/contour#30]
Is there an easier way to achieve a `MATCH_PARENT` parameter for widths and heights?

So far I've done it this way:
```
applyLayout(
    x = leftTo { parent.left() }
        .rightTo { parent.right() },
        y = topTo { parent.top() }
    )
```
But it is not straightforward and it looks like a workaround.

**Comment by aerb** [comment]
Yeah this is a common ask. I'll throw something in.
