### ISSUE TITLE
Question: How to understand ContourLayout.invoke()?

### ISSUE THREAD

**Issue by ericntw** [cashapp/contour#31]
In SampleActivity, there's `views[i]()` which calls `invoke()`.
Using breakpoints, it seems `invoke()` reinstantiate everything in SampleView1 and SampleView2
Is that correct?
Or is `invoke()` kinda redraw the view with a new state or sth like that?

Couldn't find `invoke()` function defined inside ContourLayout that's why I couldn't help myself.
Are there use cases for parameters to be passed to the `ContourLayout.invoke()` function?

**Comment by mattprecious** [comment]
This isn't a contour thing.

`views` is a list of lambdas, so when you call `views[i]()` you're invoking the lambda that creates the view, not the view itself. This is just a fancy way of creating new view instances on demand.

**Comment by saket** [comment]
Feel free to reopen this issue if you have more questions.
