### ISSUE TITLE
What's the release and distribution plan?

### ISSUE THREAD

**Issue by ericntw** [cashapp/contour#32]
Yo guys I like what I see here and want to start using this library but can't find it on either 
https://bintray.com/bintray/jcenter or search.maven.org.

**Comment by aerb** [comment]
Yeah - will push to Maven Central shortly.

**Comment by EtherBit** [comment]
Update on this?

**Comment by oldergod** [comment]
The SNAPSHOT is available [here](https://oss.sonatype.org/content/repositories/snapshots/app/cash/contour/) but can't promise anything about a versioned release yet.

**Comment by saket** [comment]
Contour is now on maven central: https://repo1.maven.org/maven2/app/cash/contour/contour/

```groovy
implementation 'app.cash.contour:contour:<version>'
```
