### ISSUE TITLE
How to update an existing view?

### ISSUE THREAD

**Issue by ericntw** [cashapp/contour#33]
It could be answered by https://github.com/cashapp/contour/issues/31
But let me single out this question here:
Consider:
```
private val name: TextView =
    TextView(context).apply {
      text = "Ben Sisko"
      setTextColor(White)
      setTextSize(TypedValue.COMPLEX_UNIT_DIP, 18f)
      applyLayout(
        x = leftTo { parent.left() + 15.dip },
        y = topTo { parent.top() + 15.dip }
      )
    }
```
How to update that name TextView to "John Doe"?

**Comment by oldergod** [comment]
You can update it the same way you would do before using Contour: `name.text = ...`
This isn't something Contour is concerned about.
