### ISSUE TITLE
wrap_content

### ISSUE THREAD

**Issue by FunnyDevs** [cashapp/contour#54]
Hi! Using 2 nested contour layout, is it possible to have something like wrap_content?

**Comment by saket** [comment]
You can use `contourHeightOf()` and pass in the last View in your hierarchy to matching the height with your content.

```kotlin
class SomeView {
  private val headerView = TextView().apply { ... }
  private val contentView = TextView().apply { ... }
  private val footerView = TextView().apply { ... }

  init {
    contourHeightOf { footerView.bottom() }
  }
}
```
