### ISSUE TITLE
Default layout width should be consistent

### ISSUE THREAD

**Issue by shaurya947** [cashapp/contour#55]
I needed a textView and a button, one below the other, both right aligned in the parent (while still respecting the left constraint of the parent's edge).

For the textView, I did the following and it worked:

```
textView.applyLayout(
    rightTo { parent.right() - 32.dip }.leftTo { parent.left() + 32.dip },
    // some YAxisSolver
)
```

The textView was wrap_content and right aligned, and if the text grew to multiple lines, the left constraint was still respected. However, doing the same for the button resulted in an always-match_parent button, even if the contents inside were much narrower. To achieve what I wanted, I had to use `SizeMode.AtMost` like so:

```
button.applyLayout(
    rightTo { parent.right() - 32.dip }.leftTo(SizeMode.AtMost) { parent.left() + 32.dip },
    topTo { textView.bottom() + 16.dip }
)
```

Why is this the case? Shouldn't the default width strategy be the same for all view types?

**Comment by mattprecious** [comment]
Looks consistent to me. Are you assuming the TextView is wrap content because it's not drawing a background?

![Screenshot_1576640466](https://user-images.githubusercontent.com/333672/71054011-6ecebf00-211e-11ea-80c6-6062f046a609.png)

```
  private val textView = TextView(context).apply {
    gravity = Gravity.END or Gravity.CENTER_VERTICAL
    text = "TextView"
  }

  private val buttonView = Button(context).apply {
    text = "Button"
  }

  override fun onInitializeLayout() {
    textView.applyLayout(
        rightTo { parent.right() - 32.dip }.leftTo { parent.left() + 32.dip },
        topTo { parent.top() + 32.dip }
    )

    buttonView.applyLayout(
        rightTo { parent.right() - 32.dip }.leftTo { parent.left() + 32.dip },
        topTo { textView.bottom() + 32.dip }
    )
  }
```

**Comment by shaurya947** [comment]
@mattprecious you're correct. I was going off the layout inspector in Android Studio which showed WRAP_CONTENT for the textView, but I later realized that it is actually the width of its parent.
