### ISSUE TITLE
View state saving inside ContourLayout

### ISSUE THREAD

**Issue by shaurya947** [cashapp/contour#56]
We recently started using contour and are really liking the no-XML approach. However, I'm a little confused as to the best way of saving state.

Say I'm using ContourLayout for my fragment like so:

```
class MyFragmentView(context: Context) : ContourLayout(context) {
    val editText1
    val editText2
    val editText3

    override fun onInitializeLayout() {
        // applyLayout calls
    }
}
```

and then in my Fragment,

```
class MyFragment : Fragment() {
    private lateinit var contourView: MyFragmentView

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = MyFragmentView(requireContext()).apply {
        contourView = this
    }

    // other fragment functions
}
```

**Now if the fragment view hierarchy is re-created (say via the Developer Options setting "Don't keep activities"), naturally, user input in the editTexts is not restored.**

To get around this, we can do:

```
class MyFragment : Fragment() {
    // other fragment functions

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putString("input1", contourView.editText1.getText())
        outState.putString("input2", contourView.editText2.getText())
        outState.putString("input3", contourView.editText3.getText())
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        savedInstanceState?.let { 
            contourView.editText1.setText(it.getString("input1"))
            contourView.editText2.setText(it.getString("input1"))
            contourView.editText3.setText(it.getString("input1"))
        }
    }
}
```

But I have a gut feeling this may not be the best way. Is there some way view state restoration can happen internally inside ContourLayout given the way we're using it in `MyFragment` above?

**Comment by saket** [comment]
Views will save their own state automatically as long as they have an ID. You can define IDs in an `ids.xml` resource file and assign them to your Contour children to enable this.

```xml
// ids.xml
<item name="some_text_field" type="id"/>
```

```kotlin
class MyFragmentView(context: Context) : ContourLayout(context) {
  val editText1 = AppCompatEditText(context).apply {
    id = R.id.some_text_field
    ...
  }
}
```

**Comment by aerb** [comment]
@saket is correct. You can generate id's using that approach, and it will auto-magically work.  I actually prefer to override `dispatchSaveInstanceState` and `dispatchRestoreInstanceState`. You can then just explicitly save and restore state as you see fit.  

```
override fun dispatchSaveInstanceState(container: SparseArray<Parcelable>) {
    container[0] = Bundle().apply {
      putString("view0", textView0.text?.toString())
      putString("view1", textView1.text?.toString())
    }
  }

  override fun dispatchRestoreInstanceState(container: SparseArray<Parcelable>) {
    val bundle = container[0] as Bundle
    textView0.setText(bundle.getString("view0"))
    textView1.setText(bundle.getString("view1"))
  }
```

**Comment by aerb** [comment]
I also have a somewhat controversial opinion on this, but views having to save and restore their state through the Android framework feels like an anti-pattern to me. You should be able to derive your view-state from database storage or in-memory caching.

**Comment by saket** [comment]
Agreed on deriving app state from persisted data, but some UI properties are transient and you may not want to persist them, like a RecyclerView's scroll position. It's not a publicly exposed property so you _can't_ store it manually either ¯\\_(ツ)_/¯.
