### ISSUE TITLE
Best practices for layout preview?

### ISSUE THREAD

**Issue by erawhctim** [cashapp/contour#69]
Given that XML isn't involved, the layout preview in studio doesn't apply here - what's the recommended way of previewing contour layouts (if any) besides building/deploying? 
Just curious if the cash app team has the same problem, has found another solution, or if its not really an issue re-deploying after making changes. 

Thanks!

**Comment by oldergod** [comment]
Before we started using Contour, the layout preview wouldn't work anyway in 99% of the cases for us so it didn't really change anything.
We try to keep stubbed UI with as little dependency as possible which we can open in "sample" apps to iterate quickly on design changes.

**Comment by saket** [comment]
Android Studio 4.2 includes a layout preview for custom views. I wonder if that's useful?

**Comment by erawhctim** [comment]
@oldergod That makes sense. 

@saket Interesting, I thought that only worked for @Composable previews - definitely worth checking out!

**Comment by vitusortner** [comment]
I got contour layouts to preview in Android Studio 4.2. In order to do so, I had to define a constructor with an `AttributeSet` and pass it into `ContourLayout`.

```kotlin
class MyView(
    context: Context,
    attrs: AttributeSet? = null
) : ContourLayout(context, attrs)
```

**Comment by azizimusa** [comment]
> I got contour layouts to preview in Android Studio 4.2. In order to do so, I had to define a constructor with an `AttributeSet` and pass it into `ContourLayout`.
> 
> ```kotlin
> class MyView(
>     context: Context,
>     attrs: AttributeSet? = null
> ) : ContourLayout(context, attrs)
> ```
i use your suggestion. The layout preview appeared. But don't know how to reflect custom layout as in the sample

![Screenshot 2020-09-25 at 11 32 35 PM](https://user-images.githubusercontent.com/6672707/94286364-7b265900-ff87-11ea-91ab-f08436de09ac.png)

**Comment by saket** [comment]
Good catch. We should make the samples preview friendly.

**Comment by Orgmir** [comment]
I am populating the views with mock data while I'm building UI using `if(isInEditMode) { ... }`. Makes the preview useful again.

Maybe you could use this to only setup Picasso if not in edit mode.

**Comment by saket** [comment]
Would anyone like to send a PR for making the sample app preview friendly?

**Comment by oh-Rin** [comment]
In fact, Android Studio 4.2 already fully supports custom view to preview, yes, any view.

As @vitusortner said, only need to define a `View` class and inherit `ContourLayout(context, null)`, subsequently, Android Studio will automatically display a preview window on the right side of the screen
