### ISSUE TITLE
Is 0.1.8 version released for public use?

### ISSUE THREAD

**Issue by kalpeshp0310** [cashapp/contour#86]
**CHANGELOG.md** Suggests that `0.1.8` version was released on 2020-06-11.
But I could not find it in maven.
Also **README.md** points to `0.1.7` version. And that makes me wonder 0.1.8 version is released for public use?

**Comment by saket** [comment]
That'd be my mistake. `0.1.8` is the upcoming version which will be released soon. You can try a SNAPSHOT in the meantime.

**Comment by kalpeshp0310** [comment]
Thanks for the update. 👍
