### ISSUE TITLE
How to use RecyclerView in contour

### ISSUE THREAD

**Issue by unDeathDream** [cashapp/contour#93]
I would be very grateful if you can give a best practices in the demo about  how to use recyclerView  in this layout

**Comment by saket** [comment]
You can use views that extend `ContourLayout` in your RecyclerView the same way as you'd use any other custom view:

```diff
class Adapter : RecyclerView.Adapter<VH> {
  override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH {
-  val itemView = LayoutInflater.from(parent.context).clone(parent.context).inflate(R.layout.item_view)
+  val itemView = ContourView(parent.context)
    return VH(itemView)
  }
}
```

**Comment by saket** [comment]
Feel free to reopen if you have more questions

**Comment by unDeathDream** [comment]
No problem✌️. Thank you very much

**Comment by unDeathDream** [comment]
No problem✌️. Thank you very much
