### ISSUE TITLE
How to make the sub view use native wrap_content?

### ISSUE THREAD

**Issue by oh-Rin** [cashapp/contour#99]
The layout api must specify the solver for the x and y axes. If I want the x axis to have similar behaviors like wrap_content, what should I do?

I only saw matchParentX/Y, why not provide wrapContentX/Y?

In native, if you don't specify width or height, LayoutParams.WRAP_CONTENT will be used by default. Can contour do the same thing?

**Comment by oh-Rin** [comment]
> Contour lays out views in wrap mode by default. For example, this will position `view` to `0, 0` of its parent and give it as much space as it wants:
> 
> ```kotlin
> view.layoutBy(
>   x = leftTo { parent.left() },
>   y = topTo { parent.top() }
> )
> ```
> 
> There are more examples in the sample app.

Thanks, but I have another question

In updateLayout, I can’t seem to call my own xy axis

thisView.updateLayout(x = leftTo {thisView.left() + 20.dip })

It will report an error CircularReferenceDebugging

**Comment by saket** [comment]
Yep, the axis solvers are supposed to be idempotent. When you're supplying updated axis solvers, they're evaluated on every subsequent layout passes. 

If that code worked, it'd move your view by 20dp every time the view hierarchy's layout was refreshed.

**Comment by oh-Rin** [comment]
@saket Sorry for being stupid, I don’t understand very well,
If the x axis of my current view is unknown,
Then I need to update the view x at some point to increase it by 20dp instead of changing x to 20dp. What should do...

**Comment by saket** [comment]
Whoops sorry I missed this. If you want to dynamically update positions, I think could try these two options:

1. Use translation that let's you make one-off adjustments to view positions:

```kotlin
view.translationX += 20.dip
```

2. Maintain some state so that you can use it in your axis solvers. Remember that your solvers may get called multiple times so they must remain idempotent.

```koltin
val isViewShifted = true/false

view.layoutBy(
  x = leftTo { parent.left() + if (isViewShifted) 20.xdip else 0.xdip }
  y = ...
)
```

**Comment by oh-Rin** [comment]
Thanks, although there are still some doubts, but I think I will use practice to solve
